version: "3.8"

services:
  xui:
    image: enwaiax/x-ui:latest
    volumes:
      - ./db:/etc/x-ui
      - ./cert:/root/cert
    restart: unless-stopped
    ports:
      - "8080:54321"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
      - "3006:3006"
      - "3007:3007"
      - "8880:8880"
      - "2052:2052"
      - "2082:2082"
      - "2086:2086"
      - "2095:2095"
